### ISSUE TITLE
prometheus adapter ApiService for custom and external metrics

### ISSUE THREAD

**Issue by Deepzima** [sighupio/fury-kubernetes-monitoring#156]
**The prometheus adapter currently does not create external and custom metrics for HPA**

In the implementation, we only define the possibility of using the most common metrics based on CPU and mem. Still, in the readme, we describe the possibility of using aggregate metrics based on other resource types Kubernetes based(custom) and external or not of type kubernetes(external) :
The Prometheus adapter provides an implementation of Kubernetes
[resource metrics](https://github.com/kubernetes/design-proposals-archive/blob/main/instrumentation/resource-metrics-api.md),
[custom metrics](https://github.com/kubernetes/design-proposals-archive/blob/main/instrumentation/custom-metrics-api.md), and
[external metrics](https://github.com/kubernetes/design-proposals-archive/blob/main/instrumentation/external-metrics-api.md) APIs.

**Comment by nutellinoit** [comment]
#157 merged, closing issue as completed
