### ISSUE TITLE
Kubernetes Cluster Grafana Dashboard should move to Calico

### ISSUE THREAD

**Issue by phisco** [sighupio/fury-kubernetes-monitoring#22]
Currently the aforementioned dashboard is showing some metrics specific to Weave-net in one of the main dashboards ("Kubernetes Cluster) which have no data point if it's not deployed.

Given that Calico is now our default standard CNI we should move this graphs to a separate dashboard if these are still relevant and add Calico related relevant metrics if necessary to the main dashboard.

**Comment by angelbarrera92** [comment]
https://trello.com/c/4C1uxp2m

**Comment by angelbarrera92** [comment]
Thanks @phisco

**Comment by angelbarrera92** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Replace networking dashboard](https://trello.com/c/4C1uxp2m/69-replace-networking-dashboard)

**Comment by lnovara** [comment]
Since https://github.com/sighupio/fury-kubernetes-monitoring/pull/29 was merged, can we close this issue?

**Comment by phisco** [comment]
yes!
