### ISSUE TITLE
kube-state-metrics not fully compatible with Kubernetes < 1.16

### ISSUE THREAD

**Issue by lnovara** [sighupio/fury-kubernetes-monitoring#32]
I noticed that kube-state-metrics 1.9.5 is supporting only Kubernetes v1.16.x.

On a 1.15.x cluster the only incompatibility is about ValidatingWebhookConfiguration, to something major but I think we should update the compatibility matrix accordingly.

Refs:
- https://github.com/kubernetes/kube-state-metrics/issues/1093
- https://github.com/kubernetes/kube-state-metrics#compatibility-matrix

**Comment by angelbarrera92** [comment]
🤦

**Comment by bogdanalov-sw** [comment]
Is it possible to get it working on 1.14.9 or it is considered too old?

**Comment by lnovara** [comment]
@bogdanalov-sw the module does work with 1.14.9 but you'll get a warning about `kube-state-metrics` not being able to scrape `ValidatingWebhookConfiguration` resources, you can safely silence it if you want.

Moreover, no functionality will be lost as none of the existing alerts depends on being able to scrape `ValidatingWebhookConfiguration`.
