### ISSUE TITLE
CPUThrottlingHigh is back

### ISSUE THREAD

**Issue by nutellinoit** [sighupio/fury-kubernetes-monitoring#68]
Hi team, we previously removed this alert, since it's only noise on clusters. https://github.com/sighupio/fury-kubernetes-monitoring/commit/23ef84624b14b597ef3fc170ab385c0366f6f1fc

But in the last release is back https://github.com/sighupio/fury-kubernetes-monitoring/blob/master/katalog/prometheus-operated/kubernetes-monitoring-rules.yml#L344

Can we remove it again? And also, let's put somewhere the list on our changes, this way on the next update we don't occur in the same problem.

**Comment by nandajavarma** [comment]
I will remove it in the coming release. Thanks Samuele!

**Comment by nutellinoit** [comment]
Awesome, thank you!

**Comment by nandajavarma** [comment]
This is merged in #71
