### ISSUE TITLE
[BUG] - Prometheus service is rendered incorrectly with kustomize

### ISSUE THREAD

**Issue by nutellinoit** [sighupio/fury-kubernetes-monitoring#83]
https://github.com/sighupio/fury-kubernetes-monitoring/blob/54c827bb85783fa2e31a5f4cb15ed0fd690efa11/katalog/prometheus-operated/deploy.yml#L67

Since we are using common labels, the prometheus generated instance from prometheus operator is without required labels to be selected from the prometheus-k8s service

**Comment by nutellinoit** [comment]
The same is happening also with alertmanager main svc

**Comment by ralgozino** [comment]
To answer my question the issue is that using `commonLabels` **also affects the `selector`**. So, then the `selector` expects the `commonLabels` that are **not** added by the Operator, resulting in the service without endpoints.

**Comment by nutellinoit** [comment]
> 

Yes, exactly 👍
